name: 'Reusable Workflow: Deploy'

on:
  workflow_call:
    inputs:
      github-environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    steps:
      - uses: actions/checkout@v4

      # Deploy steps go here

  checks:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4

      # Automated environment tests go here