name: 'Deployment: Production'

on:
  push:
    branches: [release]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  staging:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      github-environment: Production