name: 'Deployment: Test'

on:
  release:
    types: [prereleased]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      github-environment: Test